package gg.rsmod.plugins.content.areas.clanwars.shops

import gg.rsmod.plugins.content.mechanics.shops.CoinCurrency

create_shop("Zeke's Melee Store", CoinCurrency(), StockType.INFINITE) {
    items[0] = ShopItem(Items.RUNE_FULL_HELM, 100)
    items[1] = ShopItem(Items.RUNE_PLATEBODY, 100)
    items[2] = ShopItem(Items.RUNE_PLATELEGS, 100)
    items[3] = ShopItem(Items.RUNE_KITESHIELD, 100)
    items[4] = ShopItem(Items.ADAMANT_FULL_HELM, 100)
    items[5] = ShopItem(Items.ADAMANT_PLATEBODY, 100)
    items[6] = ShopItem(Items.ADAMANT_PLATELEGS, 100)
    items[7] = ShopItem(Items.ADAMANT_KITESHIELD, 100)
    items[8] = ShopItem(Items.MITHRIL_FULL_HELM, 100)
    items[9] = ShopItem(Items.MITHRIL_PLATEBODY, 100)
    items[10] = ShopItem(Items.MITHRIL_PLATELEGS, 100)
    items[11] = ShopItem(Items.MITHRIL_KITESHIELD, 100)
    items[12] = ShopItem(Items.BLACK_FULL_HELM, 100)
    items[13] = ShopItem(Items.BLACK_PLATEBODY, 100)
    items[14] = ShopItem(Items.BLACK_PLATELEGS, 100)
    items[15] = ShopItem(Items.BLACK_KITESHIELD, 100)
    items[16] = ShopItem(Items.STEEL_FULL_HELM, 100)
    items[17] = ShopItem(Items.STEEL_PLATEBODY, 100)
    items[18] = ShopItem(Items.STEEL_PLATELEGS, 100)
    items[19] = ShopItem(Items.STEEL_KITESHIELD, 100)
    items[20] = ShopItem(Items.IRON_FULL_HELM, 100)
    items[21] = ShopItem(Items.IRON_PLATEBODY, 100)
    items[22] = ShopItem(Items.IRON_PLATELEGS, 100)
    items[23] = ShopItem(Items.IRON_KITESHIELD, 100)
    items[24] = ShopItem(Items.HELM_OF_NEITIZNOT, 100)
    items[25] = ShopItem(Items.BERSERKER_HELM, 100)
    items[26] = ShopItem(Items.WARRIOR_HELM, 100)
    items[27] = ShopItem(Items.AMULET_OF_STRENGTH, 100)
    items[28] = ShopItem(Items.CLIMBING_BOOTS, 100)
    items[29] = ShopItem(Items.BARROWS_GLOVES, 100)
    items[30] = ShopItem(Items.IRON_SCIMITAR, 100)
    items[31] = ShopItem(Items.STEEL_SCIMITAR, 100)
    items[32] = ShopItem(Items.BLACK_SCIMITAR, 100)
    items[33] = ShopItem(Items.MITHRIL_SCIMITAR, 100)
    items[34] = ShopItem(Items.ADAMANT_SCIMITAR, 100)
    items[35] = ShopItem(Items.RUNE_SCIMITAR, 100)
    items[36] = ShopItem(Items.DRAGON_SCIMITAR, 100)
    items[37] = ShopItem(Items.DRAGON_DAGGERP, 100)
}