package gg.rsmod.plugins.content.areas.clanwars.shops

import gg.rsmod.plugins.content.mechanics.shops.CoinCurrency

create_shop("Lowe's Range Store", CoinCurrency(), StockType.INFINITE) {
    items[0] = ShopItem(Items.SNAKESKIN_BANDANA, 100)
    items[1] = ShopItem(Items.SNAKESKIN_BODY, 100)
    items[2] = ShopItem(Items.SNAKESKIN_CHAPS, 100)
    items[3] = ShopItem(Items.SNAKESKIN_VAMBRACES, 100)
    items[4] = ShopItem(Items.SNAKESKIN_BOOTS, 100)
    items[5] = ShopItem(Items.GREEN_DHIDE_BODY, 100)
    items[6] = ShopItem(Items.GREEN_DHIDE_CHAPS, 100)
    items[7] = ShopItem(Items.GREEN_DHIDE_VAMB, 100)
    items[8] = ShopItem(Items.BLUE_DHIDE_BODY, 100)
    items[9] = ShopItem(Items.BLUE_DHIDE_CHAPS, 100)
    items[10] = ShopItem(Items.BLUE_DHIDE_VAMB, 100)
    items[11] = ShopItem(Items.RED_DHIDE_BODY, 100)
    items[12] = ShopItem(Items.RED_DHIDE_CHAPS, 100)
    items[13] = ShopItem(Items.RED_DHIDE_VAMB, 100)
    items[14] = ShopItem(Items.BLACK_DHIDE_BODY, 100)
    items[15] = ShopItem(Items.BLACK_DHIDE_CHAPS, 100)
    items[16] = ShopItem(Items.BLACK_DHIDE_VAMB, 100)
    items[17] = ShopItem(Items.AMULET_OF_ACCURACY, 100)
    items[18] = ShopItem(Items.AVAS_ACCUMULATOR, 100)
    items[19] = ShopItem(Items.SHORTBOW, 100)
    items[20] = ShopItem(Items.OAK_SHORTBOW, 100)
    items[21] = ShopItem(Items.WILLOW_SHORTBOW, 100)
    items[22] = ShopItem(Items.MAPLE_SHORTBOW, 100)
    items[23] = ShopItem(Items.YEW_SHORTBOW, 100)
    items[24] = ShopItem(Items.MAGIC_SHORTBOW, 100)
    items[25] = ShopItem(Items.RUNE_CROSSBOW, 100)
    items[26] = ShopItem(Items.IRON_ARROW, 10999999)
    items[27] = ShopItem(Items.STEEL_ARROW, 10999999)
    items[28] = ShopItem(Items.MITHRIL_ARROW, 10999999)
    items[29] = ShopItem(Items.ADAMANT_ARROW, 10999999)
    items[30] = ShopItem(Items.RUNE_ARROW, 10999999)
    items[31] = ShopItem(Items.RUNITE_BOLTS, 10999999)
    items[32] = ShopItem(Items.DRAGONSTONE_BOLTS, 10999999)
}